name: CI/CD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker build -t your_dockerhub_username/netflix-watcher:latest .
      
    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Push Docker image
      run: docker push your_dockerhub_username/netflix-watcher:latest

    - name: Deploy to Kubernetes
      uses: appleboy/kubectl-action@v1
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        command: apply
        args: -f deployment.yaml
